version: "3.7"
services:
  monolith:
    build:
      context: .
      dockerfile: monolith.Dockerfile
    ports:
      - "12101:5000"
    volumes:
      - ./src/fit:/app/src/fit
    links:
      - monolith-db
    environment:
      - DATABASE_URL=postgresql://postgres:docker@monolith-db:5432/fit-db
      - FIT_API_KEY=some_very_secret_key
    networks:
      - fit

  coach:
    build:
      context: .
      dockerfile: coach.Dockerfile
    ports:
      - "12102:5000"
    volumes:
      - ./src/coach:/app/src/coach
    links:
      - coach-db
    environment:
      - MONOLITH_URL=http://monolith:5000
      - FIT_API_KEY=some_very_secret_key
      - DATABASE_URL=postgresql://postgres:docker@coach-db:5432/coach-db
    networks:
      - fit

  monolith-db:
    image: postgres:latest
    ports:
      - "12100:5432"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=fit-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fit-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit

  coach-db:
    image: postgres:latest
    ports:
      - "12103:5432"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=coach-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "coach-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit

networks:
  fit:
