version: "3.7"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=fit-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fit-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit
  monolith:
    build: .
    ports:
      - "5000:5000"
    environment:
      - COACH_URL=http://coach:5000
    networks:
      - fit
  coach:
    build: ./coach_service
    ports:
      - "5001:5000"
    environment:
      - MONOLITH_URL=http://monolith:5000
    depends_on:
      - monolith
    networks:
      - fit

networks:
  fit:
